/* NLAg Formulator service worker (generated by src/build.py from src/pwa/sw.template.js — edit the template, not deploy/sw.js).
   Caches the app shell so the app opens with no signal. Only same-origin files are cached: map tiles, OpenStreetMap
   field borders, imagery and elevation always come from the network (Drive mode needs signal to load new borders). */
const VERSION = 'nlag-d80556e272eb';
const SHELL = ["./", "index.html", "manifest.webmanifest", "icons/apple-touch-icon.png", "icons/favicon-32.png", "icons/icon-192.png", "icons/icon-512.png", "icons/icon-maskable-512.png"];
self.addEventListener('install', e => {
  // v18: cache: 'reload' so a new version never copies a stale file out of the browser's HTTP cache
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(SHELL.map(u => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
// v18: when this version replaces an older one, pages still running the OLD page code (v17 and before have no update bar)
// are reloaded once, so they show the new version at once instead of on the next open. Pages from v18 on say hello
// (src/gate.js: { nlagPage }) and are never reloaded by the worker; they show "Update ready — tap to reload" instead.
// Only on an update (an older nlag- cache existed), never on the first install.
const PAGES = 'nlagpages';                                   // not "nlag-…": those are the version caches cleared below
const pageKey = id => new Request(new URL('__nlag_page/' + encodeURIComponent(id), self.registration.scope).href);
const acked = new Set();
self.addEventListener('message', e => {
  const d = e.data, src = e.source; if (!d || !d.nlagPage || !src || !src.id) return;
  acked.add(src.id); e.waitUntil(caches.open(PAGES).then(c => c.put(pageKey(src.id), new Response(String(d.nlagPage)))).catch(() => null));
});
async function reloadOldPages() {
  const wins = await self.clients.matchAll({ type: 'window' }), c = await caches.open(PAGES), keys = await c.keys();
  const live = new Set(wins.map(w => pageKey(w.id).url)), known = new Set();
  await Promise.all(keys.map(r => (live.has(r.url) ? known.add(r.url) : c.delete(r))));   // forget pages that are closed
  const unknown = wins.filter(w => !known.has(pageKey(w.id).url) && !acked.has(w.id)); if (!unknown.length) return;
  unknown.forEach(w => { try { w.postMessage({ nlagPing: VERSION }); } catch (x) { /* gone */ } });   // a v18+ page that loaded a moment ago answers
  await new Promise(r => setTimeout(r, 3000));
  unknown.filter(w => !acked.has(w.id)).forEach(w => { if (w.navigate) w.navigate(w.url).catch(() => null); });
}
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(async keys => {
    const old = keys.filter(k => (k.startsWith('nlag-') && k !== VERSION) || k.startsWith('nlagtiles-'));   // tile cache off: free its space
    await Promise.all(old.map(k => caches.delete(k)));
    await self.clients.claim();
    if (old.length) reloadOldPages().catch(() => null);      // not awaited: the reload itself needs this worker active
  }));
});
// Oct 2026: shared satellite-tile cache. The zone and PI map engines read Sentinel-2 / Landsat images as byte ranges of
// 10 km image tiles, so a 250 ac field downloads ~1 GB, and every field nearby downloads the same tiles again. Byte ranges
// from the image hosts are kept here (key = host + path + range; the Planetary Computer access token in the query is
// ignored) and handed back from disk the next time — the bytes are identical, so the maps are identical. Kept to a share
// of the device's storage: when it grows past that, the cache is emptied and starts again.
const TILES = 'nlagtiles-v3', CH = 65536, TILE_HOST = /(^|\.)sentinel-cogs\.s3\.us-west-2\.amazonaws\.com$|^landsateuwest\.blob\.core\.windows\.net$|^sentinel2l2a01\.blob\.core\.windows\.net$|^naipeuwest\.blob\.core\.windows\.net$/;
// files are cut into fixed 64 KB pieces, so different fields asking for overlapping spans of the same image share pieces
let tilePuts = 0; const tileFlight = new Map();
async function tileTrim() {
  try { const est = await navigator.storage.estimate(), cap = Math.min((est.quota || 0) * 0.4, 25 * 1024 ** 3); if (est.usage > cap) await caches.delete(TILES); } catch (x) { /* no estimate: keep */ }
}
const pieceKey = (url, i) => `${self.registration.scope}__tiles/${url.host}${url.pathname}/piece-${i}`;   // (not '#': the cache ignores the part after '#')
async function piecesFromNetwork(req, url, c, i0, i1) {     // download pieces i0..i1 in one request; -> Map(i -> Uint8Array)
  const r = await fetch(new Request(req.url, { headers: { Range: `bytes=${i0 * CH}-${(i1 + 1) * CH - 1}` }, mode: 'cors', credentials: 'omit' }));
  const out = new Map(); if (r.status === 416) return out;
  if (r.status !== 206) throw new Error('no range support');
  const buf = new Uint8Array(await r.arrayBuffer());
  for (let i = i0; i <= i1; i++) { const s = (i - i0) * CH; if (s >= buf.length) break; const part = buf.slice(s, Math.min(s + CH, buf.length)); out.set(i, part);
    c.put(pieceKey(url, i), new Response(part, { headers: { 'x-len': String(part.length) } })).then(() => { if (++tilePuts % 2000 === 0) tileTrim(); }).catch(() => null); }
  return out;
}
async function tileFetch(req, url) {
  const m = /^bytes=(\d+)-(\d+)$/.exec(req.headers.get('range') || ''); if (!m) return fetch(req);
  const a = +m[1], b = +m[2], i0 = Math.floor(a / CH), i1 = Math.floor(b / CH);
  try {
    const c = await caches.open(TILES), got = new Map(), miss = [];
    for (let i = i0; i <= i1; i++) { const hit = await c.match(pieceKey(url, i)); if (hit) got.set(i, new Uint8Array(await hit.arrayBuffer())); else miss.push(i); }
    for (let k = 0; k < miss.length;) {                          // contiguous runs of missing pieces, one request each
      let e = k; while (e + 1 < miss.length && miss[e + 1] === miss[e] + 1) e++;
      const fk = `${url.host}${url.pathname}#${miss[k]}-${miss[e]}`; let p = tileFlight.get(fk);
      if (!p) { p = piecesFromNetwork(req, url, c, miss[k], miss[e]).finally(() => tileFlight.delete(fk)); tileFlight.set(fk, p); }
      for (const [i, v] of await p) got.set(i, v); k = e + 1;
    }
    const parts = []; let n = 0;                                // the bytes a..b (shorter at the end of the file, like the server)
    for (let i = i0; i <= i1; i++) { const v = got.get(i); if (!v) break; const s = i === i0 ? a - i0 * CH : 0, e = Math.min(v.length, i === i1 ? b - i1 * CH + 1 : CH); if (e > s) { parts.push(v.subarray(s, e)); n += e - s; } if (v.length < CH) break; }
    if (!n) return fetch(req);
    const body = new Uint8Array(n); let o = 0; for (const p of parts) { body.set(p, o); o += p.length; }
    return new Response(body, { status: 206, statusText: 'Partial Content', headers: { 'content-type': 'application/octet-stream', 'content-length': String(n) } });
  } catch (x) { return fetch(req); }                            // anything odd: plain network, as before
}
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) {                  // cross-origin: straight to the network, except satellite-tile byte ranges
    // (Oct 6 2026: the tile cache below is switched off — per-piece cache reads/writes made builds ~2.5x slower on
    //  Jaren's connection and the site's storage allowance is ~12 GB; kept for reference, not used)
    return;
  }
  if (req.mode !== 'navigate' && (req.cache === 'no-store' || req.cache === 'reload')) return;   // v18: the app's own update check (fetch sw.js no-store) goes to the network; a (hard) reload of the page still falls back to the cached copy offline
  if (req.mode === 'navigate') {                               // the page: network first (get updates), cached copy offline
    // v18: cache: 'no-cache' = always ask the server (a cheap 304 when nothing changed). Before v18 this used the browser's
    // HTTP cache, so for up to the host's max-age (GitHub Pages: 10 min) a normal reload could still get the old page.
    e.respondWith(fetch(req, { cache: 'no-cache' }).then(res => {
      if (res.ok) { const copy = res.clone(); caches.open(VERSION).then(c => c.put('index.html', copy)); }
      return res;
    }).catch(() => caches.match('index.html').then(hit => hit || caches.match('./'))));
    return;
  }
  if (url.pathname.endsWith('/fert-prices.json')) {           // fertilizer prices change a few times a week: network first, cached copy only offline
    e.respondWith(fetch(req, { cache: 'no-store' }).then(res => {
      if (res.ok) { const copy = res.clone(); caches.open(VERSION).then(c => c.put('fert-prices.json', copy)); }
      return res;
    }).catch(() => caches.match('fert-prices.json')));
    return;
  }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
    if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(VERSION).then(c => c.put(req, copy)); }
    return res;
  })));
});
